import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/Header";
import MaruquePage from "@/components/Maruque";
import { Bounce, ToastContainer } from "react-toastify";
import FooterPage from "@/components/Footer";

const notoSerif = Noto_Serif_Bengali({
  subsets: ["bengali", "latin"],
});

export const metadata: Metadata = {
  title: "Bazar Dord App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${notoSerif} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
        <HeaderPage />
        <MaruquePage />
        <main className="">
          {children}
          <ToastContainer
            position="top-right"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
        </main>
        <FooterPage />
      </body>
    </html>
  );
}
