import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/Header";

const notoSerif = Noto_Serif_Bengali({
  subsets: ["bengali", "latin"],
});

export const metadata: Metadata = {
  title: "Bazar Dord App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${notoSerif} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeaderPage />
        {children}
      </body>
    </html>
  );
}
